version: '3.3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345678Aa'
    ports:
      - '5432'
  python:
    image: postgres-app:latest
    restart: always
